### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#80]
### Current Behavior

- [ ] H1 missing on several pages (#82)
  - [ ] https://forschung.stadtgeschichtebasel.ch/
  - [ ] https://forschung.stadtgeschichtebasel.ch/about.html
  - [ ] https://forschung.stadtgeschichtebasel.ch/barrierefreiheitserklaerung
  - [ ] https://forschung.stadtgeschichtebasel.ch/datenschutzerklaerung
  - [ ] https://forschung.stadtgeschichtebasel.ch/ Html title could be better
- [ ] item view #88
  - [ ] Download Original missing https://forschung.stadtgeschichtebasel.ch/items/abb19765.html#metadata
  - [ ] counterintuitive ordering of "Abbildung" and "Band" in element information 
- [ ] A11y issues with color scheme. See https://pagespeed.web.dev/analysis/https-forschung-stadtgeschichtebasel-ch/2unzhfwxrx?form_factor=mobile @mtwente #92
  - [ ] Contrast
  - [ ] I missed to fill out a few yellow buttons
  - [ ] Logo link needs `aria-label=""`
  - [ ] skip-to-content button got lost somewhere along the way
  - [ ] Data Table: Pagination at the bottom has wrong colors
- [ ] "Null" showing on carousel (weird JS bug when browser tab inactive) #89
- [ ] Data Table #91
  - [ ] Multiple/compound items appear on individual rows [in the data table](https://forschung.stadtgeschichtebasel.ch/data.html), with duplicated description, title appears only for first item

- [ ] navbar #87
  - [ ] suboptimal alignment of menu button and SGB logo on smaller screens
  - [ ] turn dropdown buttons into [split dropdown buttons](https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns) to better access to browse page
replacing dropdown menu
- [ ] trigger warning: closing button not vertically centered on smaller screens #90

- [ ] Translations: #86
  - [ ] ~in~ der Zeitachse anzeigen > *auf*
  - [ ] Sortieren nach ~Zufällig~ > *Zufall*
  - [ ] "Herunterladen JPEG"

#### Incorrect data on Omeka
  - [ ] wrong title for https://forschung.stadtgeschichtebasel.ch/items/abb19004.html

#### Needs to be discussed ([Wiki](https://wiki.biozentrum.unibas.ch/display/dgpsgb/2024-04-10+Workshop+Forschungsdatenplattform))
- [ ] navbar
  - [ ] suggestion: swap "Bibliographie" (external content) and "Daten" (internal content)
  - [ ] maybe add timeline, eras, ... pages to the top of browse page, 
  - [ ] Logo placement: portal vs. platform (Cristina)
- [ ] items
  - [ ] [Nicht im Onlinekatalog verzeichnet](https://forschung.stadtgeschichtebasel.ch/items/Nicht%20im%20Onlinekatalog%20verzeichnet) linked from https://forschung.stadtgeschichtebasel.ch/items/abb19765.html
- [ ] Metadata: wrong citation format (Cristina)
- [ ] Back Buttons (Cristina)
- [ ] check for consistent wording: Objekt, Item, Ressource, Element
